/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AttachmentMarkdownContent: typeof import('./src/components/AttachmentMarkdownContent.vue')['default']
    CallDock: typeof import('./src/components/CallDock.vue')['default']
    ChatArea: typeof import('./src/components/ChatArea.vue')['default']
    ConnectionBanner: typeof import('./src/components/ConnectionBanner.vue')['default']
    DictionariesTab: typeof import('./src/components/admin/DictionariesTab.vue')['default']
    DocumentCard: typeof import('./src/components/documents/DocumentCard.vue')['default']
    DocumentsShell: typeof import('./src/components/documents/DocumentsShell.vue')['default']
    DocumentsSidebar: typeof import('./src/components/documents/DocumentsSidebar.vue')['default']
    DocumentsTreeNode: typeof import('./src/components/documents/DocumentsTreeNode.vue')['default']
    FieldsPanel: typeof import('./src/components/admin/FieldsPanel.vue')['default']
    IosInstallGuide: typeof import('./src/components/IosInstallGuide.vue')['default']
    MembersPanel: typeof import('./src/components/MembersPanel.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MultiSelect: typeof import('./src/components/tasks/MultiSelect.vue')['default']
    NotificationLevelSelector: typeof import('./src/components/NotificationLevelSelector.vue')['default']
    PwaUpdateBanner: typeof import('./src/components/PwaUpdateBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SidebarItem: typeof import('./src/components/SidebarItem.vue')['default']
    SortIcon: typeof import('./src/components/tasks/SortIcon.vue')['default']
    StatusesTab: typeof import('./src/components/admin/StatusesTab.vue')['default']
    TaskAttachments: typeof import('./src/components/tasks/TaskAttachments.vue')['default']
    TaskCard: typeof import('./src/components/tasks/TaskCard.vue')['default']
    TaskComments: typeof import('./src/components/tasks/TaskComments.vue')['default']
    TaskCreateDialog: typeof import('./src/components/tasks/TaskCreateDialog.vue')['default']
    TaskDescriptionEditor: typeof import('./src/components/tasks/TaskDescriptionEditor.vue')['default']
    TaskDescriptionRichEditor: typeof import('./src/components/tasks/TaskDescriptionRichEditor.vue')['default']
    TaskFieldInput: typeof import('./src/components/tasks/TaskFieldInput.vue')['default']
    TaskKanbanView: typeof import('./src/components/tasks/TaskKanbanView.vue')['default']
    TaskListView: typeof import('./src/components/tasks/TaskListView.vue')['default']
    TaskRow: typeof import('./src/components/tasks/TaskRow.vue')['default']
    TaskTrackerFilters: typeof import('./src/components/tasks/TaskTrackerFilters.vue')['default']
    TaskTrackerShell: typeof import('./src/components/tasks/TaskTrackerShell.vue')['default']
    TaskTrackerSidebar: typeof import('./src/components/tasks/TaskTrackerSidebar.vue')['default']
    TeamspacesView: typeof import('./src/components/documents/TeamspacesView.vue')['default']
    TemplatesTab: typeof import('./src/components/admin/TemplatesTab.vue')['default']
    ThreadPanel: typeof import('./src/components/ThreadPanel.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
