/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    CallDock: typeof import('./src/components/CallDock.vue')['default']
    ChatArea: typeof import('./src/components/ChatArea.vue')['default']
    ConnectionBanner: typeof import('./src/components/ConnectionBanner.vue')['default']
    DictionariesTab: typeof import('./src/components/admin/DictionariesTab.vue')['default']
    FieldsPanel: typeof import('./src/components/admin/FieldsPanel.vue')['default']
    MembersPanel: typeof import('./src/components/MembersPanel.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MultiSelect: typeof import('./src/components/tasks/MultiSelect.vue')['default']
    PwaUpdateBanner: typeof import('./src/components/PwaUpdateBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SidebarItem: typeof import('./src/components/SidebarItem.vue')['default']
    SortIcon: typeof import('./src/components/tasks/SortIcon.vue')['default']
    StatusesTab: typeof import('./src/components/admin/StatusesTab.vue')['default']
    TaskAttachments: typeof import('./src/components/tasks/TaskAttachments.vue')['default']
    TaskCard: typeof import('./src/components/tasks/TaskCard.vue')['default']
    TaskComments: typeof import('./src/components/tasks/TaskComments.vue')['default']
    TaskCreateDialog: typeof import('./src/components/tasks/TaskCreateDialog.vue')['default']
    TaskFieldInput: typeof import('./src/components/tasks/TaskFieldInput.vue')['default']
    TaskListView: typeof import('./src/components/tasks/TaskListView.vue')['default']
    TaskRow: typeof import('./src/components/tasks/TaskRow.vue')['default']
    TaskTrackerSidebar: typeof import('./src/components/tasks/TaskTrackerSidebar.vue')['default']
    TemplatesTab: typeof import('./src/components/admin/TemplatesTab.vue')['default']
    ThreadPanel: typeof import('./src/components/ThreadPanel.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
